name: build_and_deploy

on:
  push:
    branches: [main]
  # (opsional) biar jalan juga saat PR ke main:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Show node & npm
        run: |
          node -v
          npm -v

      - name: Create .env for Vite
        run: |
          cat > .env << 'EOF'
          VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
          EOF

      - name: Install deps (npm ci)
        run: npm ci

      - name: List files (debug)
        run: |
          ls -la
          ls -la node_modules/.bin || true
          cat package.json

      - name: Check vite (debug)
        run: |
          npx --yes vite --version || true

      - name: Build (prefer npm script, fallback npx)
        run: |
          npm run build || npx --yes vite@5.4.19 build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TABUNGIN_YUK }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
